version: '3'
services:
  nginx:
    # image: ubuntu:22.04
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - SecretMessagingStaticFiles:/static
    networks:
      - proxynetwork
    # command: ["tail", "-f", "/dev/null"]
networks:
  proxynetwork:
    external: true
volumes:  
  SecretMessagingStaticFiles:
    external: true