version: '3'
services:
  wasm-builder:
    build:
      context: .
      dockerfile: BackendBuilder.Dockerfile
    volumes:
      - ./SecretMessagingBackEnd:/source
      - ./build/:/build
      - SecretMessagingCommonFiles:/output
    command: bash -c "emcmake cmake -S /source -B /build && cd /build && make && chown -R 1000:1000 /build \
      && cp /build/SecretMessagingBackEnd.* /output"
volumes:
  SecretMessagingCommonFiles:
    external: true